title: OccuSys Workshop @ ACM BuildSys 2026
description: Occupant-Centric Energy Systems (OccuSys) â€“ Modeling and Control Beyond Static Boundaries

baseurl: "/buildsys2026"
url: "https://occusys.github.io"

markdown: kramdown
permalink: pretty

nav:
  - title: Home
    url: /
  - title: Call for Papers
    url: /call/
  - title: Important Dates
    url: /dates/
  - title: Submission
    url: /submission/
  - title: Committee
    url: /committee/
  - title: Program
    url: /program/
  - title: Contact
    url: /contact/
